apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: evolution-api
  annotations:
    github.com/project-slug: verbeux-ai/evolution-api
spec:
  type: other
  lifecycle: unknown
  owner: guests
